name: Require PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  require-pr-checks:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
